vpc-name      = "Jenkins-vpc"
igw-name      = "Jenkins-igw"
subnet-name   = "Jenkins-subnet"
rt-name       = "Jenkins-route-table"
sg-name       = "Jenkins-sg"
instance-name = "Jenkins-server"
key-name      = "jenkins-key"
iam-role      = "Jenkins-iam-role"
private-subnet-id = "subnet-xxxxxxxx" # Replace with your private subnet ID
security-group-id = "sg-xxxxxxxx" # Replace with your security group ID
